project:
  type: website
  output-dir: docs

website:
  title: "John Waczak, PhD"
  navbar:
    background: primary
    search: true
    right:
      - text: Home
        href: index.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: Montserrat



